[build]
  command = "bun install && bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]
